REFPLTB-1474
rdkcentral/meta-turris pull request #371
Opened 2021-12-06 07:48 UTC by rnaren94

REFPLTB-1474: Task to stabilize opensync 2.4.5 on Turris omnia and upstream it to meta-turris

2021-12-07 18:42 UTC, manigandanj requested changes
Don't remove this opensync_2.0.5.bbappend until meta-rdk-opensync in manifest XML is updated to point to osync_2.4.5

2021-12-07 18:42 UTC, manigandanj commented on recipes-connectivity/opensync/opensync_2.4.5.bbappend
> +#FILESEXTRAPATHS_prepend := "${THISDIR}/opensync_2.4.5:${THISDIR}/files:"
please remove this line.

2021-12-16 09:17 UTC, scthunderbolt commented
Please have a meaningful subject line in the commit-msg.

2021-12-17 14:30 UTC, manigandanj requested changes

2021-12-17 14:30 UTC, manigandanj commented on recipes-connectivity/opensync/opensync_2.4.5.bbappend
> +#FILESEXTRAPATHS_prepend := "${THISDIR}/opensync_2.4.5:${THISDIR}/files:"
please remove this line.

2023-12-18 14:08 UTC, scthunderbolt commented
Closed due to inactivity, please restore if still needed.

2023-12-18 14:08 UTC, closed without merging