Update ccsp-eth-agent for wan-manager support
rdkcentral/meta-turris pull request #382
Opened 2022-01-11 14:06 UTC by KaviyaKumaresan

REFPLTB-1505: Add necessary updates for WanManager support in meta-turris layer

Reason for change: Including the changes for wanmanager integeration
Test Procedure: Build and test
Risks: low

Signed-off-by: KaviyaKumaresan <Kaviya.Kumaresan@ltts.com>

2022-01-11 14:59 UTC, scthunderbolt commented on recipes-ccsp/ccsp/ccsp-eth-agent.bbappend
> +FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
Missing SRC_URI to fetch the patch file.

2022-01-11 15:14 UTC, KaviyaKumaresan commented on recipes-ccsp/ccsp/ccsp-eth-agent.bbappend
> +FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
I have added, Thanks!

2022-01-11 18:35 UTC, manigandanj approved these changes

2022-01-11 18:39 UTC, manigandanj requested changes

2022-01-11 18:39 UTC, manigandanj commented on recipes-ccsp/ccsp/ccsp-eth-agent.bbappend
> +SRC_URI_append = " file://include_platform_turris.patch"
please append ";apply=no"

2022-01-12 04:02 UTC, KaviyaKumaresan commented on recipes-ccsp/ccsp/ccsp-eth-agent.bbappend
> +SRC_URI_append = " file://include_platform_turris.patch"
Included, Kindly review

2022-01-12 07:10 UTC, manigandanj approved these changes

2022-01-12 07:11 UTC, merged