REFPLTB-1764: Upgrade ath10k firmware
rdkcentral/meta-turris pull request #471
Opened 2022-08-11 18:31 UTC by vineet-seth

Remove the hardcoding to SRCREV so that latest firmware is always selected.

2022-08-15 08:08 UTC, scthunderbolt requested changes

2022-08-15 08:08 UTC, scthunderbolt commented on recipes-kernel/linux-firmware-ath10k/linux-firmware-ath10k_git.bb
> +SRCREV = "${AUTOREV}"
Please use a SHA1 commit for SRCREV, otherwise it would not be easily reproducible in future releases.

2022-08-15 13:50 UTC, vineet-seth commented on recipes-kernel/linux-firmware-ath10k/linux-firmware-ath10k_git.bb
> +SRCREV = "${AUTOREV}"
Done. Marked with the latest firmware commit O/p of ethtool -i wlan1 : 10.2.4-1.0-00047

2022-08-16 08:10 UTC, scthunderbolt approved these changes

2022-08-17 14:57 UTC, manigandanj approved these changes

2022-08-17 14:58 UTC, merged